apiVersion: apps/v1
kind: Deployment
metadata:
  name: karci-webapp
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: karci-webapp
        image: aozcalisan/karciwebapp:2023-01-11--15-52
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007